DotNetCore_5/DotNetCore_5/Controllers/BookingController.cs
using DotNetCore_5.DAL;
using DotNetCore_5.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using X.PagedList;

namespace DotNetCore_5.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private readonly IWebHostEnvironment _iWebHostEnvironment;
        ICustomer _iCustomerRepository;
        IVehicles _iVehiclesRepository;
        IBooking _IbookingRepository;
        public BookingController(IWebHostEnvironment iWebHostEnvironment, IBooking ibookingRepository,ICustomer iCustomerRepository, IVehicles iVehiclesRepository)
        {
            this._iWebHostEnvironment = iWebHostEnvironment;
            this._iCustomerRepository = iCustomerRepository;
            this._iVehiclesRepository = iVehiclesRepository;
            this._IbookingRepository = ibookingRepository;
        }
        public IActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            IEnumerable<BookingViewModel> booking = _IbookingRepository.GetAll();
            ViewBag.Customer = _iCustomerRepository.GetAll();
            ViewBag.Vehicel = _iVehiclesRepository.GetAll();
            int slNo = 1;
            foreach (var item in booking)
            {
                item.SerialNo = slNo++;
                item.FullName = item.FirstName +" "+ item.LastName;
                item.Total = (int)item.DailyHireRate * item.TotalDaysOfHiring;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                booking = booking.Where(e => e.FullName.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    booking = booking.OrderByDescending(e => e.City).ToList();
                    break;
                default:
                    booking = booking.OrderBy(e => e.Address).ToList();
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
           
            return View(booking.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookingViewModel objModel)
        {
            if (ModelState.IsValid)
            {

                _IbookingRepository.Save(objModel);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            IEnumerable<CustomerViewModel> listOfCustomer = _iCustomerRepository.GetAll();
            ViewBag.Customer = listOfCustomer;
            IEnumerable<VehicleViewModel> listOfVehicel = _iVehiclesRepository.GetAll();
            ViewBag.Vehicel = listOfVehicel;
            BookingViewModel booking = _IbookingRepository.GetById(id);
            ViewBag.Details = "Show";
            return PartialView("~/Views/Booking/_Edit.cshtml", booking);
        }
        [HttpPost]
        public IActionResult Edit(BookingViewModel obj)
        {
            if (ModelState.IsValid)
            {
                _IbookingRepository.Update(obj);
            }
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int id)
        {
           
            _IbookingRepository.Delete(id);
            return RedirectToAction("Index");

        }
        public PartialViewResult Details(int id)
        {
            IEnumerable<CustomerViewModel> listOfCustomer = _iCustomerRepository.GetAll();
            ViewBag.Customer = listOfCustomer;
            IEnumerable<VehicleViewModel> listOfVehicel = _iVehiclesRepository.GetAll();
            ViewBag.Vehicel = listOfVehicel;
            BookingViewModel vehicle = _IbookingRepository.GetById(id);

            return PartialView("~/Views/Booking/_Details.cshtml", vehicle);

        }
        public JsonResult GetCustomer()
        {
           
            return Json(_iCustomerRepository.GetAll());
        }
        public JsonResult GetAllById(int CustomerId)
        {
            
            return Json(_iCustomerRepository.GetById(CustomerId));
        }
        public JsonResult GetVehicel()
        {

            return Json(_iVehiclesRepository.GetAll());
        }
        public JsonResult GetById(int VehicleID)
        {

            return Json(_iVehiclesRepository.GetById(VehicleID));

        }

    }
}

DotNetCore_5/DotNetCore_5/Controllers/PaymentTypeController.cs
using DotNetCore_5.DAL;
using DotNetCore_5.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore_5.Controllers
{
    [Authorize]
    public class PaymentTypeController : Controller
    {
        IPaymentType _IPaymentRepository;
        public PaymentTypeController(IPaymentType paymentRepository)
        {
            _IPaymentRepository = paymentRepository;
        }
        public IActionResult Index()
        {
            return View(_IPaymentRepository.GetAll());
        }
        [HttpPost]
        public IActionResult Create(PaymentTypeViewModel obj)
        {
            if (ModelState.IsValid)
            {
                _IPaymentRepository.Insert(obj);
            }
            return PartialView("_PaymentTypeList", _IPaymentRepository.GetAll());
        }
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            PaymentTypeViewModel obj = _IPaymentRepository.GetById(id);
            ViewBag.Details = "Show";
            return PartialView("~/Views/PaymentType/_Edit.cshtml", obj);
        }
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult PostEdit(PaymentTypeViewModel obj)
        {
            var result = false;
            if (obj.PaymentTypeCode > 0)
            {
                if (ModelState.IsValid)
                {
                    _IPaymentRepository.Update(obj);
                    result = true;
                }
            }
            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        public PartialViewResult Delete(int id)
        {
            PaymentTypeViewModel obj = _IPaymentRepository.GetById(id);
            ViewBag.Details = "Show";
            return PartialView("~/Views/PaymentType/_Delete.cshtml", obj);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult PostDelete(PaymentTypeViewModel obj)
        {
            _IPaymentRepository.Delete(obj.PaymentTypeCode);
            return RedirectToAction("Index");
        }
    }
}

DotNetCore_5/DotNetCore_5/Controllers/ReportController.cs
using DotNetCore_5.DAL;
using FastReport.Data;
using FastReport.Export.PdfSimple;
using FastReport.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using static DotNetCore_5.DAL.Repositories;
using static DotNetCore_5.Models.AllModels.Models;

namespace DotNetCore_5.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly IConfiguration iConfiguration;
        private readonly IWebHostEnvironment iWebHostEnvironment;
        private readonly ICustomer iCustomer;
        public ReportController(IConfiguration _iConfiguration, IWebHostEnvironment _iWebHostEnvironment, ICustomer _iCustomer)
        {
            iConfiguration = _iConfiguration;
            iWebHostEnvironment = _iWebHostEnvironment;
            iCustomer = _iCustomer;
        }
        public IActionResult Report()
        {
            var webReport = GetReport();
            ViewBag.WebReport = webReport;
            return View();
        }
        public WebReport GetReport()
        {
           var webReport=new WebReport();
            var msqlDataConnection = new MsSqlDataConnection();
            msqlDataConnection.ConnectionString = iConfiguration.GetConnectionString("DefaultConnection");
            webReport.Report.Dictionary.Connections.Add(msqlDataConnection);
            webReport.Report.Load(Path.Combine(iWebHostEnvironment.ContentRootPath, "Reports", "Customer.frx"));
            var customer = iCustomer.GetAll();
            webReport.Report.RegisterData(customer, "Customers");
            return webReport;
        }
        public IActionResult Pdf()
        {
            var webReport = GetReport();
            webReport.Report.Prepare();

            using (MemoryStream ms = new MemoryStream())
            {
                PDFSimpleExport pdfExport = new PDFSimpleExport();
                pdfExport.Export(webReport.Report, ms);
                ms.Flush();
                return File(ms.ToArray(), "application/pdf", Path.GetFileNameWithoutExtension("Master-Detail") + ".pdf");
            }
        }
    }
}

DotNetCore_5/DotNetCore_5/Controllers/VehicelController.cs
using DotNetCore_5.DAL;
using DotNetCore_5.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace DotNetCore_5.Controllers
{
    [Authorize]
    public class VehicelController : Controller
    {
        private readonly IWebHostEnvironment _iWebHostEnvironment;
        IVehicles _iVehicleRepository;
        IVechileImage _iVehicelImage;
        public VehicelController(IWebHostEnvironment iWebHostEnvironment, IVehicles iVehicleRepository, IVechileImage iVehicelImage)
        {
            _iWebHostEnvironment = iWebHostEnvironment;
            _iVehicleRepository = iVehicleRepository;
            _iVehicelImage = iVehicelImage;
        }
        public IActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            IEnumerable<VehicleViewModel> list = _iVehicleRepository.GetAll();
            int slNo = 1;
            foreach (var item in list)
            {
                item.SerialNo = slNo++;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                list = list.Where(e => e.Model.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(e => e.Manufacturer).ToList();
                    break;
                default:
                    list = list.OrderBy(e => e.Manufacturer).ToList();
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));

        }

        [HttpPost]

        public IActionResult Create(VehicleViewModel objModel)
        {

            string uniqueImageName = null;
            bool result = false;
            if (ModelState.IsValid)
            {
                VehicleViewModel vehicleViewModel = _iVehicleRepository.Save(objModel);
                VechileImageViewModel imagemodel = new VechileImageViewModel();
                if (objModel.Photos != null && objModel.Photos.Count > 0)
                {
                    foreach (IFormFile photo in objModel.Photos)
                    {
                        string uploadFolder = Path.Combine(_iWebHostEnvironment.WebRootPath, "images/vehicel_images");
                        uniqueImageName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                        string filePath = Path.Combine(uploadFolder, uniqueImageName);
                        FileStream fileStream = new FileStream(filePath, FileMode.Create);
                        photo.CopyTo(fileStream);
                        fileStream.Close();
                        imagemodel.VehicleID = vehicleViewModel.VehicleID;
                        imagemodel.ImageName = uniqueImageName;
                        _iVehicelImage.Save(imagemodel);

                    }
                }
                result = true;
            }
            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {

            VehicleViewModel vehicle = _iVehicleRepository.GetById(id);
            ViewBag.Images = _iVehicelImage.GetImagesId(id);
            return View(vehicle);
        }
        [HttpPost]
        public IActionResult Edit(VehicleViewModel objModel)
        {
            string uniqueImageName = null;
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.VehicleID > 0)
                {
                    VehicleViewModel returnObj = _iVehicleRepository.Update(objModel);
                    VechileImageViewModel imageObj = new VechileImageViewModel();
                    if (objModel.Edit_Photos != null && objModel.Edit_Photos.Count > 0)
                    {
                        foreach (IFormFile photo in objModel.Edit_Photos)
                        {
                            string uploadFolder = Path.Combine(_iWebHostEnvironment.WebRootPath, "images/vehicel_images");
                            uniqueImageName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                            string filePath = Path.Combine(uploadFolder, uniqueImageName);
                            FileStream fileStream = new FileStream(filePath, FileMode.Create);
                            photo.CopyTo(fileStream);
                            fileStream.Close();
                            imageObj.VehicleID = returnObj.VehicleID;
                            imageObj.ImageName = uniqueImageName;
                            _iVehicelImage.Save(imageObj);
                        }
                    }
                    result = true;
                }
              

            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        public IActionResult Delete(int id)
        {
            if (id > 0)
            {
                var Images = _iVehicelImage.GetImagesId(id);
                if (Images != null)
                {
                    foreach (var image in Images)
                    {
                        if (image.ImageName != null)
                        {
                            string uploadFolder = Path.Combine(_iWebHostEnvironment.WebRootPath, "images/vehicel_images");
                            DeleteExistingImage(Path.Combine(uploadFolder, image.ImageName));
                        }
                        _iVehicelImage.Delete(image.ImageId);
                    }
                }
                _iVehicleRepository.Delete(id);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ErrorMessage = "Vehicel is not deleted";
                return RedirectToAction("Message");
            }
        }
        public IActionResult DeleteImage(int id)
        {
            var image = _iVehicelImage.GetById(id);
            if (image.ImageName != null)
            {
                string uploadFolder = Path.Combine(_iWebHostEnvironment.WebRootPath, "images/vehicel_images");
                DeleteExistingImage(Path.Combine(uploadFolder, image.ImageName));
            }
            _iVehicelImage.Delete(image.ImageId);
            return RedirectToAction("Edit", new { id = image.VehicleID });
        }
        private void DeleteExistingImage(string imagePath)
        {
            FileInfo fileObj = new FileInfo(imagePath);
            if (fileObj.Exists)
            {
                fileObj.Delete();
            }
        }
        public PartialViewResult Details(int id)
        {

            VehicleViewModel vehicle = _iVehicleRepository.GetById(id);
            ViewBag.Images = _iVehicelImage.GetImagesId(id);
            return PartialView("~/Views/Vehicel/_Details.cshtml", vehicle);

        }
        public PartialViewResult ViewImages(int id)
        {
            IEnumerable<VechileImageViewModel> obj = _iVehicelImage.GetImagesId(id);
            ViewBag.ViewImages = "Show";
            return PartialView("~/Views/Vehicel/_ViewImages.cshtml", obj);
        }
    }
}

DotNetCore_5/DotNetCore_5/Views/Shared/NotFound.cshtml
<br />
<h3>@ViewBag.ErrorMessage</h3>

DotNetCore_5/DotNetCore_5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Rental Management</title>

    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/jquery/jquery.js"></script>

    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

    <script src="~/CustomJS/JavaScript.js"></script>
    <script src="~/CustomJS/Image.js"></script>
    <link href="~/css/imageCss.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Tech Cars</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Customer" asp-action="Index">Customer</a>
                                </li>
                                <li>
                                    <a class="nav-link" asp-controller="Report" asp-action="Report">Report</a>
                                </li>
                            }
                            if (User.IsInRole("User"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Vehicel" asp-action="Index">Vehicel</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Booking" asp-action="Index">Booking</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="PaymentType" asp-action="Index">Payment Type</a>
                                </li>
                            }

                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="Index">Administrator</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Customer" asp-action="Index">Customer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Vehicel" asp-action="Index">Vehicel</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Booking" asp-action="Index">Booking</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="PaymentType" asp-action="Index">Payment Type</a>
                            </li>
                            <li>
                                <a class="nav-link" asp-controller="Report" asp-action="Report">Report</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tech Cars - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>